seeder:
  file: ./seeder/seeder.rb
  disabled: false

parsers:
  - file: ./parsers/listing.rb
    page_type: 'listings'
    disabled: false
  - file: ./parsers/products.rb
    page_type: 'products'
    disabled: false    

exporters:
  - file: ./exporters/product_json.yaml